from tkinter import *
from tkinter import messagebox as a
root=Tk()
def ak(event):
    global val
    text=event.widget.cget("text")
    if text=="=":
        if val.get().isdigit():
            value=int(val.get())
        else:
            try:
                value=eval(screen.get())
                val.set(value)
                screen.update()
            except Exception as e:
                a.showerror("wrong input","invalid syntex")
            return
        
        
        
    elif text=="C":
        val.set("")
        screen.update()
        
    else:
        val.set(val.get()+ text)
        screen.update()
    
root.geometry("230x440")
root.title("my calculator")
val=StringVar()
val.set("")
######1
f=Frame(root,bg="red")
screen=Entry(f,textvar=val,font="lucida 24 bold")
screen.pack(fill=X,ipadx=8,pady=15,padx=15)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="9",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="8",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="7",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="6",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="5",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="4",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="3",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="2",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="1",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="0",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="-",padx=5,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="+",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="*",padx=5,pady=3,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="/",padx=6,pady=3,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="C",padx=1,pady=2,font="lucida 22 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
b=Button(f,text="%",padx=7,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="=",padx=2,pady=2,font="lucida 24 bold")
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",ak)
f.pack()
root.mainloop()
